#!/bin/bash

docker build -t sample_particles -f DockerfileParticles .
docker build -t sample_ocean -f DockerfileOceanFFT .
docker build -t sample_nbody -f DockerfileNbody .
docker build -t sample_mandelbrot -f DockerfileMandelbrot .
docker build -t sample_randomfog -f DockerfileRandomFog .
docker build -t device_query -f DockerfileDeviceQuery .
