#!/bin/bash

sudo ./tx2-docker run sample_particles &
sudo ./tx2-docker-ocean run sample_ocean &
sudo ./tx2-docker run sample_nbody &
sudo ./tx2-docker run sample_mandelbrot &
sudo ./tx2-docker run sample_marchingcubes &
sudo ./tx2-docker run sample_randomfog &

